version: '3.8'

services:
  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBAPP_URL=http://localhost:3000
    volumes:
      - ./api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_API_URL=http://localhost:8000
    volumes:
      - ./web:/app
    depends_on:
      - backend
    command: npm run dev
    # command: npm start